### ISSUE TITLE
open pdf directly

### ISSUE THREAD

**Issue by scott-glancy** [ShawnGeller/QIJC-1#1]
On the Vote page, can you add links that open the papers' pdfs in new tabs?  This will save me a couple of mouse clicks and web page loads during the meetings.

**Comment by scott-glancy** [comment]
Can you add an editable Announcements section to the Home page? On the old site, I used this to make notes about the meeting room, teleconference link, and other announcements.

**Comment by ShawnGeller** [comment]
Done, I think

**Comment by scott-glancy** [comment]
The new links look like they should go to the pdf, but the url actually points to the abs page.

**Comment by scott-glancy** [comment]
Nevermind.  I just remembered that I have a Firefox add-on that converts urls that point to arXiv pdfs to urls that point to abs pages.  With the add-on turned off, the new links work correctly.
