### ISSUE TITLE
false error message when deleting an account

### ISSUE THREAD

**Issue by scott-glancy** [ShawnGeller/QIJC-1#10]
I just deleted the "admin" account, and I got this message:

> 3
> 
> \<User admin>
> 
> An unexpected error has occurred

Nevertheless, the "admin" account is now gone.

**Comment by ShawnGeller** [comment]
Could not reproduce this error, can you try again and let me know if the problem persists?

**Comment by scott-glancy** [comment]
I just created a normal user account and then retired it without seeing any error message.  I also created an admin account and retired it without any error message.

One difference between my test today and the deletion that created the error message is that earlier I was deleting an account from the UMD version of the website.

I guess you can close this issue because we can't replicate it, and it did not cause any harm in the first place.
