### ISSUE TITLE
email sending

### ISSUE THREAD

**Issue by scott-glancy** [ShawnGeller/QIJC-1#13]
I don't seem to be getting email sent by the Messaging page.  I tried to send the abstracts twice today, but I did not get any email.

**Comment by ShawnGeller** [comment]
I tried a few things, but I don't want to send out an unnecessary email blast. Can you try next week and let me know how it goes?

**Comment by scott-glancy** [comment]
Yes.  Actually I have been trying every week, just in case.  Also I have never been sure if the problem is that the emails are not being sent to anyone or if the email is somehow not arriving in my inbox.

**Comment by scott-glancy** [comment]
I just clicked on the "Send" button, but I did not get any email. :(

**Comment by ShawnGeller** [comment]
Oh gosh, and there's nothing in the error log. I'll have to dive a little deeper to figure this one out.

**Comment by scott-glancy** [comment]
In my opinion, email sending is not an essential function of the website.

**Comment by ShawnGeller** [comment]
Be that as it may, I think I've actually fixed it this time.

**Comment by scott-glancy** [comment]
It is nice to have, so thanks!

**Comment by scott-glancy** [comment]
I just tried to send email.  The webpage says "Message sent.", but I didn't see it in my inbox.
