### ISSUE TITLE
announcements

### ISSUE THREAD

**Issue by scott-glancy** [ShawnGeller/QIJC-1#2]
Can you add an editable Announcements section to the Home page? On the old site, I used this to make notes about the meeting room, teleconference link, and other announcements.

**Comment by scott-glancy** [comment]
It would accomplish most of my goals if we could just put the meeting time and Google Meet link (https://meet.google.com/amv-ytut-kit) on the Home page.  Making it editable is not necessary.

**Comment by ShawnGeller** [comment]
Done.
