### ISSUE TITLE
changing email address

### ISSUE THREAD

**Issue by scott-glancy** [ShawnGeller/QIJC-1#8]
When I tried to change my email address, and "unexpected error" occurred.

**Comment by ShawnGeller** [comment]
Can you try again? I can't reproduce this.

**Comment by scott-glancy** [comment]
I tried again to change my address to scott.glancy@nist.gov, and I got the "unexpected error" again.  I then tried to change my address to scott@glancys.net, and that was successful.  I then changed it to sglancy@nist.gov, and that was successful.  I then tried again to change to scott.glancy@nist.gov, but that failed.

**Comment by scott-glancy** [comment]
I just realized that there is another account that uses scott.glancy@nist.gov.  This was the old "admin" account on the UMD server. Because the new site gives administrator powers to real accounts, I will just delete the "admin" account.

**Comment by scott-glancy** [comment]
I just deleted the "admin" account, and I got this message:
 
> 3
> 
> <User admin>
> 
> An unexpected error has occurred

Nevertheless, the admin account is now gone, and I was able to change my email address.
